services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=100.126.235.13:3003,localhost:3003
    volumes:
      - ./config:/app/config
    ports:
      - "3003:3000"

networks:
  homelab:
    external: true
