services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - SIGNUPS_ALLOWED=true
    volumes:
      - ./data:/data
    ports:
      - "3002:80"

networks:
  homelab:
    external: true
