services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__ROOT_URL=http://100.126.235.13:3001/
    volumes:
      - ./data:/data
    ports:
      - "3001:3000"
      - "2222:22"

networks:
  homelab:
    external: true
